friendlyFire: false

world: "world"

spectatorSpawn:
  x: 0.0
  y: 0.0
  z: 0.0

red:
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  wool:
    x: 0.0
    y: 0.0
    z: 0.0
  members:
    - archiebaldry

blue:
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  wool:
    x: 0.0
    y: 0.0
    z: 0.0
  members:
    - Zom3g
