main: archiebaldry.WoolBattle.WoolBattle
name: WoolBattle
version: 1.0

author: archiebaldry

commands:
  join:
    usage: /join <team> [player]
  leave:
    usage: /leave [player]
  start:
    usage: /start
