main: archiebaldry.WoolBattle.WoolBattle
name: Wool Battle
version: 1.0-SNAPSHOT

author: archiebaldry

commands:
  join:
    usage: /join <team> [player]
  leave:
    usage: /leave [player]
  start:
    usage: /start